config/routes.rb
Rails.application.routes.draw do
  resources :stories, except: [:update, :destroy, :edit]
  root to: "pages#index"
  namespace :admin do
    root to: "stories#index"
    resources :stories
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/story.rb
class Story < ApplicationRecord
end

app/controllers/admin/stories_controller.rb
class Admin::StoriesController < ApplicationController
  http_basic_authenticate_with name: Settings.basic_auth_user, password: Settings.basic_auth_password
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  # GET /admin/stories
  # GET /admin/stories.json
  def index
    @stories = Story.order(id: :desc).all
  end

  # GET /admin/stories/1
  # GET /admin/stories/1.json
  def show
  end

  # GET /admin/stories/1/edit
  def edit
  end

  # PATCH/PUT /admin/stories/1
  # PATCH/PUT /admin/stories/1.json
  def update
    if @story.update(story_params)
      redirect_to edit_admin_story_path(@story), notice: 'История успешно обновлена!'
    else
      render :edit
    end
  end

  # DELETE /admin/stories/1
  # DELETE /admin/stories/1.json
  def destroy
    @story.destroy
    redirect_to admin_stories_url, notice: 'История успешно удалена' 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def story_params
      params.require(:story).permit(:name, :city, :age, :content, :allow_public_read, :is_published)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  # GET /
  def index
    @stories = Story.where(is_published: true).order(id: :desc)
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.where(is_published: true).order(id: :desc).page(params[:page]).per(5)
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
    @story = Story.find(params[:id])
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params)

    if @story.save
      redirect_to new_story_path, notice: 'Спасибо за вашу историю! Скоро мы ее проверим и опубликуем.'
    else
      render :new
    end
  end

  private
    # Only allow a list of trusted parameters through.
    def story_params
      params.require(:story).permit(:name, :city, :age, :content, :allow_public_read, :is_published)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
  def author_info(story)
    name = story.name.present? ? story.name : 'Анонимно'
    age = story.age.present? ? ", #{story.age}" : ''
    city = story.city.present? ? ", #{story.city}" : ''
    name + age + city
  end
end

app/views/admin/stories/_form.html.erb
<%= form_with(url: admin_story_path, model: story, local: true) do |form| %>
<% if story.errors.any? %>
<div class="error" id="error_explanation">
  <h2><%= pluralize(story.errors.count, "error") %> Не получается сохранить историю:</h2>
  <ul>
    <% story.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class='form_content admin'>
  <div class="field">
    <div class='label'><%= form.label :name, 'Имя' %></div>
    <%= form.text_field :name, :class => 'input' %>
  </div>

  <div class="field">
    <div class='label'><%= form.label :city, 'Город' %></div>
    <%= form.text_field :city, :class => 'input' %>
  </div>

  <div class="field">
    <div class='label'><%= form.label :age, 'Возраст' %></div>
    <%= form.number_field :age, :class => 'input' %>
  </div>

  <div class="field">
    <div class='label'><%= form.label :content, 'История' %></div>
    <%= form.text_area :content, rows: "6", :class => 'textarea' %>
  </div>

  <div class="field">
    <div class='label inline'><%= form.label :is_published, 'Опубликовано' %></div>
    <%= form.check_box :is_published %>
  </div>

  <div class="actions">
    <%= form.submit  value='Сохранить', :class => 'btn' %>
  </div>
</div>
<% end %>

app/views/admin/stories/edit.html.erb
<div class='admin_page content-wrapper'>
  <% if notice %>
  <p id="notice" class='notice'><%= notice %></p>
  <% end %>
  <h1 class='main_header'>Редактировать историю</h1>

  <%= render 'form', story: @story %>

  <%= link_to admin_stories_path do %>
  <i class="fa fa-arrow-left" aria-hidden="true"> <span>Назад к историям</spa> </i>
  <% end %>
</div>

app/views/admin/stories/index.html.erb
<div class='admin_page content-wrapper'>
  <% if notice %>
  <p id="notice" class='notice'><%= notice %></p>
  <% end %>
  <h2 class='main_header'>Истории</h2>

  <table>
    <thead>
      <tr>
        <th>Имя</th>
        <th>Город</th>
        <th>Возраст</th>
        <th>История</th>
        <th>Опубликовано?</th>
        <th colspan="3">Действия</th>
      </tr>
    </thead>

    <tbody>
      <% @stories.each do |story| %>
      <tr>
        <td><%= story.name %></td>
        <td><%= story.city %></td>
        <td><%= story.age %></td>
        <td><%= story.content.truncate_words(4, omission: '').sub!(/[?.!,;]?$/, '') + '...' %></td>
        <td><%= story.is_published ? 'да' : 'нет' %></td>

        <td><%= link_to  edit_admin_story_path(story) do %>
          <i class="fas fa-edit"></i>
          <% end %></td>
        <td><%= link_to admin_story_path(story), method: :delete, data: { confirm: 'Вы уверены, что хотите удалить эту историю?' } do %>
          <i class="fas fa-trash-alt"></i>
          <% end %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Имя:</strong>
  <%= @story.name %>
</p>

<p>
  <strong>Город:</strong>
  <%= @story.city %>
</p>

<p>
  <strong>Возраст:</strong>
  <%= @story.age %>
</p>

<p>
  <strong>История:</strong>
  <%= @story.content %>
</p>

<p>
  <strong>Опубликовано?</strong>
  <%= @story.is_published %>
</p>

<%= link_to 'Edit', edit_admin_story_path(@story) %> |
<%= link_to 'Back', admin_stories_path %>

app/views/common/_footer.html.erb
<footer class="black-bg">
  <div class="content-wrapper">
    <div class="text">
      Наши партнеры:
    </div>
    <div class="teatr_doc">
      <%= image_tag  "LOGO_TEATRDOC_WHITE.svg", class: "teatr_doc_img", alt: 'teatr.doc' %>
    </div>
    <div class="opia">
      <%= image_tag  "opia_LOGO-17-white-1.png", class: "opia_img", alt: 'opia' %>
    </div>
    <div class="postpictures">
      <%= image_tag  "post-logo-white-alpha-1.png", class: "postpictures_img", alt: 'postpictures' %>
    </div>
  </div>
</footer>

app/views/common/_header.html.erb
<header>
  <div class="logo">
    <a href="/">ЛАВР</a>
  </div>
  <div class="menu">
    <%= link_to "О ПРОЕКТЕ", root_path(anchor: 'about'), class: 'menu_item' %>
    <%= link_to "EVENT", root_path(anchor: 'event'), class: 'menu_item' %>
    <%= link_to "ИСТОРИИ", root_path(anchor: 'stories'), class: 'menu_item' %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Л А В Р</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta property="og:title" content="Л А В Р">
  <meta property="og:description" content="Лавр — проект о жертвах сталкинга.">
  <meta property="og:image" content="<%= image_path('social_media.png') %>">
  <meta property="og:url" content="https://laavr.herokuapp.com/">


  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= favicon_link_tag asset_path('favicon.ico') %>
</head>

<body>
  <%= yield %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://kit.fontawesome.com/0703e88282.js" crossorigin="anonymous"></script>
</body>

</html>

app/views/pages/index.html.erb
<div class="first-screen">
  <%= render 'common/header' %>
  <div class="text">
    ЛАВР
  </div>
</div>
<div>
  <section id="about" class='about'>
    <div class="content-wrapper">
      <h2 class="main_header">
        Не ходи за мной
      </h2>
      <p>&laquo;Лавр&raquo;&nbsp;&mdash; трансмедийный проект о&nbsp;сталкинге. О&nbsp;нежелательном, навязчивом внимании, преследовании. Мир сильно изменился, из&nbsp;анонимной среды обитания он&nbsp;превратился в&nbsp;пространство, где каждый может узнать о&nbsp;тебе всё. Цифровая прозрачность, доступность любой информации&nbsp;&mdash; наша новая реальность, к&nbsp;которой мы&nbsp;пока не&nbsp;сумели адаптироваться. Этика&nbsp;&mdash; не&nbsp;технология, она не&nbsp;успевает меняться так быстро. Пока мы&nbsp;не&nbsp;поняли устройства новых личных границ, мы&nbsp;продолжаем пользоваться ими по&nbsp;своему усмотрению. </p>
      <p>В&nbsp;первую очередь это игровой фильм&nbsp;&mdash; о&nbsp;преследовании, с&nbsp;которым может столкнуться каждый. О&nbsp;навязчивом, переходящем привычные нам границы способе привлечения внимания и&nbsp;демонстрации власти. О&nbsp;новой прозрачности и&nbsp;отсутствии приватности. И&nbsp;о&nbsp;невозможности сделать с&nbsp;этим что-либо в&nbsp;рамках существующей системы. Работая над сценарием, мы&nbsp;опирались на&nbsp;опыт и&nbsp;истории людей, которые прошли через такое вторжение в&nbsp;свою жизнь или испытывают его сейчас, а&nbsp;также постарались разобраться в&nbsp;мотивах преследователей. </p>
      <p>Поддержать съёмки фильма можно <a href='https://planeta.ru/campaigns/lavr' target="_blank">на&nbsp;краудфандинговой платформе &laquo;Планета&raquo;</a>. Слоган нашей кампании &nbsp;&mdash; &laquo;Не&nbsp;ходи за&nbsp;мной&raquo;, и&nbsp;она о&nbsp;силе и&nbsp;смелости, которая необходима для того, чтобы дать преследователю вербальный отпор, и&nbsp;о&nbsp;законодательной системе, которая не&nbsp;видит в&nbsp;феномене преследования проблемы. Мы&nbsp;собирали лоты, которые отражали&nbsp;бы наши ценности,&nbsp;&mdash; вы&nbsp;найдете их&nbsp;на&nbsp;странице проекта. </p>
      <p>Авторы проекта: Егор Исаев, Анна Беркова</p>
      <div class="btn-wrap">
        <a href='https://planeta.ru/campaigns/lavr' target="_blank" class='btn'>Поддержать</a>
      </div>
    </div>
  </section>

  <section id="event" class="event black-bg">
    <div class="content-wrapper">
      <h2 class="main_header">
        Сталкинг. Вторая серия.
      </h2>

      <p>
        Режиссёр: Вера Пирогова
      </p>
      <p>Сталкинг&nbsp;&mdash; нежелательное, навязчивое внимание, преследование. </p>
      <p>Спектакль сделан в&nbsp;технике вербатима&nbsp;&mdash; это интервью, дословно воспроизведенные актерами на&nbsp;сцене. Это монологи людей, которые сталкивались с&nbsp;преследованием, и&nbsp;тех, кто сам осуществлял подобные действия, грубо нарушая чужие границы и&nbsp;не&nbsp;видя в&nbsp;этом проблемы. Истории разные&nbsp;&mdash; странные и&nbsp;местами смешные, неоднозначные и&nbsp;романтичные. Страшные. Герои по-разному переживают ситуацию, кто-то с&nbsp;юмором, кто-то с&nbsp;пугающим хладнокровием, кто-то не&nbsp;может справиться с&nbsp;тревожностью до&nbsp;сих пор. </p>
      <p>На&nbsp;этот раз мы&nbsp;сконцентрировались на&nbsp;преследовании, которое осуществляют бывшие партнеры и&nbsp;партнерши. Это наиболее частый вид сталкинга&nbsp;&mdash; и&nbsp;самый опасный. Преследователи считают, что отношения, которые были до, дают им&nbsp;право преследовать свою бывшую или бывшего. Люди, оказавшиеся в&nbsp;такой ситуации, еще более беззащитны, чем&nbsp;те, кого преследуют незнакомцы. И&nbsp;это может коснуться всех нас&nbsp;&mdash; все мы&nbsp;вступаем в&nbsp;отношения и&nbsp;никто не&nbsp;защищен от&nbsp;таких ситуаций. В&nbsp;спектакле прозвучат голоса психолога и&nbsp;полицейского, которые имели дело с&nbsp;подобными ситуациями&nbsp;&mdash; как начало большого разговора о&nbsp;том, какие превентивные меры могут быть внедрены законодательно, а&nbsp;какие можем принимать мы&nbsp;сами, как можем отслеживать &laquo;звоночки&raquo; и&nbsp;не&nbsp;бояться публично говорить о&nbsp;проблеме, если это уже случилось. </p>
      <p>10&nbsp;мая состоится показ второй серии, в&nbsp;которой будут рассказаны новые истории.</p>

      <div class="register">
        <div class='info_block'>
          <div class="title">
            Дата и время
          </div>
          <div class="info">
            10 мая 2021, 13:00
          </div>
        </div>
        <div class="line"></div>
        <div class='info_block'>
          <div class="title">
            Место
          </div>
          <div class="info">
            Театр.doc на острове, Садовническая набережная, 69
          </div>
        </div>
        <div class="line"></div>
        <a href="https://www.teatrdoc.ru/schedule/1081/" target="_blank" class="btn">
          Билеты
        </a>
      </div>
    </div>
  </section>

  <section id="stories" class="stories">
    <div class="content-wrapper">
      <h2 class="main_header">
        Истории
      </h2>
      <p>Мы&nbsp;всегда просим друг друга написать, когда доберемся до&nbsp;дома, не&nbsp;садимся на&nbsp;переднее сиденье такси, баним незнакомцев в&nbsp;инстаграме&nbsp;&mdash; и&nbsp;это наша повседневность. Мы&nbsp;вынуждены жить, постоянно помня о&nbsp;том, что кто-то в&nbsp;любой момент может нарушить наши границы и&nbsp;даже не&nbsp;осознать, что в&nbsp;этом есть какая-то проблема. Если в&nbsp;вас это откликается&nbsp;&mdash; напишите. Давайте слушать друг-друга.</p>
      <div class="btn-wrap">
        <%= link_to "Поделиться", new_story_path, class: 'btn' %>
      </div>

      <% @stories.each_with_index do |story, index| %>
      <div class="stories-block">
        <div class="story <%= index%2 == 1 ? 'right' : '' %>">
          <div class="text">
            <%= story.content %>
          </div>
          <div class="author">
            <%= author_info(story) %>
          </div>
        </div>
      </div>
      <% end %>

      <% if @stories.present? %>
      <div class="in_case_of">
        <p>Если с&nbsp;вами произошла подобная история и&nbsp;вы&nbsp;не&nbsp;знаете, куда обратиться&nbsp;&mdash; вот проекты, которые могут вам помочь.</p>
        <div class="links">
          <a href="https://nasiliu.net/" target="_blank">Насилию.нет</a>
          <a href="https://tineodna.ru/" target="_blank">ТыНеОдна</a>
          <a href="http://www.sisters-help.ru/" target="_blank">Сестры</a>
        </div>
      </div>
    </div>
    <% end %>
</div>
</section>

<%= render 'common/footer' %>
</div>

app/views/stories/_form.html.erb
<%= form_with(model: story, local: true, class: 'form') do |form| %>
<% if story.errors.any? %>
<div class="error" id="error_explanation">
  <h2>История не может быть отправлена:</h2>

  <ul>
    <% story.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class='form_content'>
  <div class="form__group field">
    <%= form.text_field :name, :class => 'form__field', :placeholder => 'Имя' %>

    <div class='form__label'><%= form.label :name, 'Имя' %></div>
  </div>

  <div class="form__group field">
    <%= form.text_field :city, :class => 'form__field', :placeholder => 'Город' %>

    <div class='form__label'><%= form.label :city, 'Город' %></div>
  </div>

  <div class="form__group field">
    <%= form.text_field :age, :class => 'form__field', :placeholder => 'Сколько вам лет?' %>

    <div class='form__label'><%= form.label :age, 'Сколько вам лет?' %></div>
  </div>

  <div class="form__group field">
    <%= form.text_area :content, :class => 'form__field text_area', :placeholder => 'Ваша история', rows: 1 %>

    <div class='form__label'><%= form.label :content, 'Ваша история' %></div>
  </div>

  <div class="actions">
    <%= form.submit value='Отправить', :class => 'btn' %>
  </div>
</div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing Story</h1>

<%= render 'form', story: @story %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<%= render 'common/header' %>

<section class="black-bg">
  <div class="content-wrapper">
    <h2 class="main_header">
      Истории
    </h2>
    <p>Мы&nbsp;всегда просим друг друга написать, когда доберемся до&nbsp;дома, не&nbsp;садимся на&nbsp;переднее сиденье такси, баним незнакомцев в&nbsp;инстаграме&nbsp;&mdash; и&nbsp;это наша повседневность. Мы&nbsp;вынуждены жить, постоянно помня о&nbsp;том, что кто-то в&nbsp;любой момент может нарушить наши границы и&nbsp;даже не&nbsp;осознать, что в&nbsp;этом есть какая-то проблема. Если в&nbsp;вас это откликается&nbsp;&mdash; напишите. Давайте слушать друг-друга.</p>
    <div class="btn-wrap">
      <%= link_to "Поделиться", new_story_path, class: 'btn' %>
    </div>
  </div>

</section>
<section id="stories" class="stories">
  <div class="content-wrapper">
    <h2 class="main_header">
      Ваши истории
    </h2>
    <% @stories.each_with_index do |story, index| %>
    <div class="stories-block">
      <div class="story <%= index%2 == 1 ? 'right' : '' %>">
        <div class="text">
          <%= story.content %>
        </div>
        <div class="author">
          <%= author_info(story) %>
        </div>
      </div>
    </div>
    <% end %>
    <%= paginate @stories %>
  </div>
</section>

<%= render 'common/footer' %>

app/views/stories/new.html.erb
<div class='new_story black-bg'>
  <%= render 'common/header' %>

  <div class='content-wrapper -all-screen-height'>
    <h2 class='main_header'>Поделись своей историей</h2>

    <%= render 'form', story: @story%>
  </div>
  <%= render 'common/footer' %>
</div>

<% if notice %>
<div class='popup_wrapper'>
  <div class="popup">
    <div class="popup_content">
      <%= notice %>
      <%= link_to "Ок", new_story_path, class: 'btn' %>
    </div>
  </div>
</div>
<% end %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @story.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @story.city %>
</p>

<p>
  <strong>Age:</strong>
  <%= @story.age %>
</p>

<p>
  <strong>Content:</strong>
  <%= @story.content %>
</p>

<p>
  <strong>Allow public read:</strong>
  <%= @story.allow_public_read %>
</p>

<p>
  <strong>Is public:</strong>
  <%= @story.is_published %>
</p>